services:

  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: "rootpassword"
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    networks: 
      - app-network

  app:
    #image: thelab-app:latest  # Utilisez le nouveau nom d'image
    build:
      context: .
    ports:
      - "3310:${APP_PORT}"
    environment:
      APP_PORT: ${APP_PORT}
      APP_SECRET: ${APP_SECRET}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      SECRET_KEY_JWT: ${SECRET_KEY_JWT}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
    depends_on:
      - database
    restart: always
    networks: 
      - app-network
      
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"  # Redirige les requêtes HTTP depuis le port 80 vers Nginx
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Montre un fichier de configuration personnalisé
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app  # Nginx démarre après l'application
    networks: 
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email khouani.nadir7@gmail.com -d thelab-academy.fr --agree-tos

  certbot-renew:
      image: certbot/certbot
      container_name: certbot-renew
      volumes:
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/certbot
      entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet && nginx -s reload; sleep 12h & wait $!; done"

volumes:
  db-data:

networks:
  app-network:
    driver: bridge